version: '3.7'
services:
  database:
    image: postgres
    container_name: database_miakhats
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=mia
      - POSTGRES_PASSWORD=mia
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/src/infra/database/schema.sql
      - pgdata:/data/postgres

  live-reload:
    image: web-dev
    container_name: server_miakhats
    build: .
    environment:
      PORT: 4000
    command:
      - npm
      - run
      - live-reload
    ports:
      - 4000:4000
    volumes:
      - .:/web-dev
      - node_modules:/web-dev/node_modules
    links:
      - database
    depends_on: 
      - database
    restart: always

  test-watch:
    image: web-dev
    build: .
    environment:
      PORT: 4000
    command:
      - npm
      - run
      - test:watch
    volumes:
      - .:/web-dev
      - node_modules:/web-dev/node_modules
    ports:
      - 4000:4000

volumes:
  node_modules: {}
  pgdata: 
    driver: local
